### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by boctok** [bm1549/home-assistant-frigidaire#48] opened 2024-01-29 11:43 UTC
I replaced the integration with the updated one, restarted HA and tried to add the integration, but I keep getting "Failed to connect". There is nothing in the logs.

**Comment by ha-elguano** [comment] 2024-01-29 17:03
I just noticed @rothn's updates to the integration as well, and implementing the changes didn't work for me. The only difference seemed to be I now no longer get an explicit failure in the Integrations tab, but the Frigidaire dehumidifier entity still shows up as "no longer being provided by the integration."

**Comment by rothn** [comment] 2024-01-31 04:18
This looks like a duplicate of https://github.com/bm1549/home-assistant-frigidaire/issues/49#issuecomment-1918003436 . Check there and submit logs on the issue or privately over Matrix if you want to help fix the issue. An API changed and I did not have a dehumidifier to test on.

**Closed** 2024-06-16 01:35 UTC
