### ISSUE TITLE
"Failed to connect" on setup flow

### ISSUE THREAD

**Issue by amaisano** [bm1549/home-assistant-frigidaire#33] opened 2023-06-02 05:53 UTC
I'm getting an instant failure when submitting my username (email) and password.

I tried debugging with the package locally with Postman, and the same headers/auth is giving me a 401 - Unauthorized response.

Did this break recently?

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.2
Frontend 20230503.3 - latest

No other info in debugging logs in HA (yes I have it all enabled for debugging - logger and integration debugging for HACS).

**Comment by boctok** [comment] 2023-06-02 10:17
There was a recent update to the LG ThinQ app on your phone that requires accepting updated terms of service. Your HA integration won't connect until you have tapped accept on your phone app.

**Comment by marty22877** [comment] 2023-06-02 12:50
LG ThinQ app?  Do you mean the frigidaire app?

And i'm seeing the same thing

**Comment by amaisan0** [comment] 2023-06-02 12:50
LG?? But I have no LG stuff...

**Comment by fouram** [comment] 2023-06-02 13:56
Same thing just started happening to me, app still works but suddenly my integration fails 401. No changes to password.
`Traceback (most recent call last):
  File "/config/custom_components/frigidaire/__init__.py", line 20, in setup
    hass.data[DOMAIN][entry.entry_id] = frigidaire.Frigidaire(
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 246, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 282, in authenticate
    auth_response = self.post_request('/authentication/authenticate', data)
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 429, in post_request
    return self.parse_response(response)
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 403, in parse_response
    raise FrigidaireException(f'Request failed with status {response.status_code}: {response.content}')
frigidaire.FrigidaireException: Request failed with status 401: b'{"message":"Unauthorized"}'`

Endpoint URLs changed?

**Comment by amaisano** [comment] 2023-06-02 14:13
When I was fooling around with Postman, I used a POST (not GET) to the test_connection `{path}` and I got back some interesting warnings about missing amazon parameters. Maybe related?

**Comment by Spenser715** [comment] 2023-06-02 15:24
I too am experiencing this issue. It was working fine yesterday and stopped today. I don't believe there were any updates that would have caused this.

**Comment by Conundrum1911** [comment] 2023-06-02 15:29
Same -- First day I needed to use my dehumidifier this year and I noticed it offline in Home Assistant, but working on the iPhone app.  Tried reloading the integration which failed, and removed it and went to re-add and it won't let me anymore.

Seems like whatever changed, it happened in the last 24 hours.

**Comment by thejevans** [comment] 2023-06-02 15:48
It seems like this hit another package using the Electrolux API, too.

[mauro-midolo/homeassistant_electrolux_status/issues/115](https://github.com/mauro-midolo/homeassistant_electrolux_status/issues/115) 

[tomeko12/pyelectroluxconnect/issues/13](https://github.com/tomeko12/pyelectroluxconnect/issues/13) 

This either needs to be fixed in [bm1549/frigidaire](https://github.com/bm1549/frigidaire) or we need to switch to using [tomeko12/pyelectroluxconnect](https://github.com/tomeko12/pyelectroluxconnect) as suggested in #27 .

**Comment by jazzmonger** [comment] 2023-06-02 16:24
Same problem here.  Failed to connect.

**Comment by sirjmann92** [comment] 2023-06-02 20:09
Same issue. Was working fine yesterday. Today I'm seeing "Failed to set up" but the Frigidaire app is still fine (haven't had to reauthenticate).

Log:
```
Error setting up entry frigidaire for frigidaire
Traceback (most recent call last):
  File "/config/custom_components/frigidaire/__init__.py", line 20, in setup
    hass.data[DOMAIN][entry.entry_id] = frigidaire.Frigidaire(
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 246, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 282, in authenticate
    auth_response = self.post_request('/authentication/authenticate', data)
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 429, in post_request
    return self.parse_response(response)
  File "/usr/local/lib/python3.10/site-packages/frigidaire/__init__.py", line 403, in parse_response
    raise FrigidaireException(f'Request failed with status {response.status_code}: {response.content}')
frigidaire.FrigidaireException: Request failed with status 401: b'{"message":"Unauthorized"}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/frigidaire/__init__.py", line 28, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/frigidaire/__init__.py", line 26, in setup
    raise data_entry_flow.AbortFlow from err
TypeError: AbortFlow.__init__() missing 1 required positional argument: 'reason'
```

**Comment by bm1549** [comment] 2023-06-02 22:18
Unfortunately, https://github.com/tomeko12/pyelectroluxconnect has the same issue as we do right now

I'll see if I can figure out a fix here, but I don't have my jailbroken phone anymore so it may be difficult 😢

**Comment by bm1549** [comment] 2023-06-02 22:32
Does anyone have a jailbroken mobile device? I can walk you through the process of sniffing requests

**Comment by thejevans** [comment] 2023-06-03 00:49
> Does anyone have a jailbroken mobile device? I can walk you through the process of sniffing requests

@bm1549 I don't have that, but I just set up waydroid and wireshark on my laptop and got the frigidaire app installed.

**Comment by jethri** [comment] 2023-06-03 00:56
Anecdotally, for me the iOS Frigidaire 2.0 app won't let me login, but the new(?) app does.  
This one: https://apps.apple.com/us/app/frigidaire/id1599494923

**Comment by bm1549** [comment] 2023-06-03 00:57
> > Does anyone have a jailbroken mobile device? I can walk you through the process of sniffing requests
> 
> @bm1549 I don't have that, but I just set up waydroid and wireshark on my laptop and got the frigidaire app installed.

The frigidaire app does SSL certificate pinning, so that's not sufficient

**Comment by thejevans** [comment] 2023-06-03 01:20
can we get around that with Frida?

**Comment by bm1549** [comment] 2023-06-03 01:23
According to [this blog](https://redfoxsec.com/blog/ssl-pinning-bypass-android-frida/) you can. It says your device needs to be rooted though

**Comment by danielschwartz** [comment] 2023-06-03 02:55
Just want to +1 that this is happening to me as well (and is also affecting karlg100/homebridge-frigidaire) so i'm guessing this was a change on the Frigidaire side

**Comment by justinmyersm** [comment] 2023-06-03 15:52
> Anecdotally, for me the iOS Frigidaire 2.0 app won't let me login, but the new(?) app does. This one: https://apps.apple.com/us/app/frigidaire/id1599494923

I did receive an email back in early March about having to migrate to the new 2.0 app. 

>Frigidaire
To our Valued Frigidaire Family Members,
We’ve made important updates to our Frigidaire App!
In case you missed it, an enhanced version of your Frigidaire App is now available. In order to access the enhanced security features, you will need to reset your password. 
Simply, open your app, click on “Forgot Password” to update your credentials. Enjoy exploring your new Frigidaire 2.0 app!

Sounds like something server side. 

> Just want to +1 that this is happening to me as well (and is also affecting [karlg100/homebridge-frigidaire](https://github.com/karlg100/homebridge-frigidaire)) so i'm guessing this was a change on the Frigidaire side

Probably has something to do with migrating to the new 2.0 app?

**Comment by DevGary** [comment] 2023-06-03 22:41
I submitted a potential [fix](https://github.com/bm1549/frigidaire/pull/18) but I could not find a way to test it in HASS.

**Comment by bm1549** [comment] 2023-06-04 04:08
Can someone try #34 to see if the issue is resolved?

**Comment by jethri** [comment] 2023-06-04 04:37
I think it worked?!   

<img width="399" alt="image" src="https://github.com/bm1549/home-assistant-frigidaire/assets/57852106/14f4c494-f996-4145-9aa3-abe96a2d67eb">

Disclaimer...I'm new to HA/integrations/github...the only change I saw is the frigidaire == version # in the manifest saw I made that same change (via nano in terminal), restarted, tried to login, and it worked.

I did try to use the home-assistant-frigidaire/tree/bm1549-patch-1 as an integration in HACS but it seemed to just pull the main branch of the repo.  

I would feel better if someone who had it working before (and might better know how to test it) would confirm 😅

**Comment by sirjmann92** [comment] 2023-06-04 11:56
Seems to have worked for me by manually updating manifest.json as @jethri suggested. And like them, I have no idea how to do this properly by pulling new files so I manually updated the manifest.json file and everything seems to be working again (authentication, automations, entities, cards, etc.).

My HA is in a Docker container on a Synology NAS,

Steps I took to fix it (requires Text Editor from Package Center).
1. Open Synology DSM
2. Open File Station
3. Navigate to the frigidaire custom components directory of my docker install for HA (volume1/docker/homeassistant/custom_components/frigidaire)
4. Open manifest.json in Text Editor
5. Change this code:
```
    "frigidaire==0.18.12"
```
to this:
```
    "frigidaire==0.18.13"
```
6. Save the manifest.json file
7. Restart HA
8. Navigate to Settings -> Devices & Services
9. Click Integrations
10. Search for Frigidaire
11. Enter credentials from Frigidaire app
12. Success!
13. Tested all previous integrations and automations
14. Success!

So it's really just updating the version in the manifest.json file.

For a career, I'm a Product Manager that works with dev and test teams to deliver proprietary software for one of the largest ISPs in the US, and one of the biggest complaints we have is versioning of upstream dependencies breaking shit when teams don't communicate their changes for their consumers/clients. This case is obviously not the same as multiple internal teams but it's just as annoying.

I'm glad you found a quick fix @bm1549 and thanks to everyone for posting and contributing.

It would be nice if this integration (or some other Frigidaire integration) was part of HA core code so using Watchtower on the Docker container would pull these changes in automatically without having to do custom stuff. But alas, a working solution is better than none :)

**Comment by marty22877** [comment] 2023-06-04 12:48
That fixed it.  And I work for a software company too in the development
area, I had a chuckle when I read your email and it ended up just being
that one character.  It's amazing how much that happens in the software
world and nobody has any idea.

**Closed** 2023-06-04 13:57 UTC

**Comment by bm1549** [comment] 2023-06-04 13:59
For posterity, that library is a reverse engineered version of the Frigidaire API that I maintain

@DevGary is the one who actually found the fix and pushed it up in https://github.com/bm1549/frigidaire/pull/18 !

**Comment by amaisano** [comment] 2023-06-04 18:16
I told my wife yesterday there was an elite group of devs working to fix this problem. She called you all not the "A Team," but the "A-C team." She thought she was very clever.

Thanks all for getting this obscure API working again <3

**Comment by jazzmonger** [comment] 2023-06-05 16:38
Confirmed.  That works.

**Comment by jazzmonger** [comment] 2024-05-30 00:35
Well... it was working.  same problem again.

I had to bump the version again:

```{
  "version": "0.1.0",
  "domain": "frigidaire",
  "name": "frigidaire",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/frigidaire",
  "requirements": [
    "frigidaire==0.18.14"   <-----------------
```
